// <auto-generated />
using System;
using BookShop.Server.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookShopManagementSystem.Server.Migrations
{
    [DbContext(typeof(BookShopAPIContext))]
    partial class BookShopAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookShop.Server.Models.Book", b =>
                {
                    b.Property<int>("BookID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookID"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BookCategoryID")
                        .HasColumnType("int");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pages")
                        .HasColumnType("int");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SellingPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookID");

                    b.HasIndex("BookCategoryID");

                    b.ToTable("Book");

                    b.HasData(
                        new
                        {
                            BookID = 1,
                            Author = "F. Scott Fitzgerald",
                            BookCategoryID = 1,
                            ISBN = "978-0743273565",
                            ImageUrl = "",
                            Pages = 180,
                            Publisher = "Scribner",
                            PurchasePrice = 250.00m,
                            SellingPrice = 450.00m,
                            Stock = 50,
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            BookID = 2,
                            Author = "Harper Lee",
                            BookCategoryID = 1,
                            ISBN = "978-0061120084",
                            ImageUrl = "/images/books/mockingbird.jpg",
                            Pages = 324,
                            Publisher = "Harper Perennial",
                            PurchasePrice = 300.00m,
                            SellingPrice = 500.00m,
                            Stock = 40,
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            BookID = 3,
                            Author = "Yuval Noah Harari",
                            BookCategoryID = 2,
                            ISBN = "978-0062316110",
                            ImageUrl = "/images/books/sapiens.jpg",
                            Pages = 443,
                            Publisher = "Harper",
                            PurchasePrice = 400.00m,
                            SellingPrice = 650.00m,
                            Stock = 30,
                            Title = "Sapiens"
                        },
                        new
                        {
                            BookID = 4,
                            Author = "Stephen Hawking",
                            BookCategoryID = 3,
                            ISBN = "978-0553380163",
                            ImageUrl = "/images/books/brief-history.jpg",
                            Pages = 256,
                            Publisher = "Bantam",
                            PurchasePrice = 350.00m,
                            SellingPrice = 550.00m,
                            Stock = 25,
                            Title = "A Brief History of Time"
                        },
                        new
                        {
                            BookID = 5,
                            Author = "Willem van Schendel",
                            BookCategoryID = 4,
                            ISBN = "978-9840515752",
                            ImageUrl = "/images/books/bangladesh-history.jpg",
                            Pages = 392,
                            Publisher = "Cambridge University Press",
                            PurchasePrice = 500.00m,
                            SellingPrice = 800.00m,
                            Stock = 20,
                            Title = "The History of Bangladesh"
                        });
                });

            modelBuilder.Entity("BookShop.Server.Models.BookCategory", b =>
                {
                    b.Property<int>("BookCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookCategoryID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookCategoryID");

                    b.ToTable("BookCategory");

                    b.HasData(
                        new
                        {
                            BookCategoryID = 1,
                            Name = "Fiction"
                        },
                        new
                        {
                            BookCategoryID = 2,
                            Name = "Non-Fiction"
                        },
                        new
                        {
                            BookCategoryID = 3,
                            Name = "Science"
                        },
                        new
                        {
                            BookCategoryID = 4,
                            Name = "History"
                        });
                });

            modelBuilder.Entity("BookShop.Server.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@bookshop.com",
                            Password = "admin123",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("BookShop.Server.Models.Book", b =>
                {
                    b.HasOne("BookShop.Server.Models.BookCategory", "BookCategory")
                        .WithMany("Books")
                        .HasForeignKey("BookCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookCategory");
                });

            modelBuilder.Entity("BookShop.Server.Models.BookCategory", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
